name: release
description: release maltmill
inputs:
  tag:
    description: tag name to be released
    default: ''
  token:
    description: GitHub token
    required: true
runs:
  using: composite
  steps:
  - name: setup go
    uses: actions/setup-go@be3c94b385c4f180051c996d336f57a34c397495 # v3.6.1
    with:
      go-version-file: go.mod
  - name: build
    run: |
      make crossbuild
    shell: bash
  - name: upload
    run: |
      make upload
    shell: bash
    env:
      GITHUB_TOKEN: ${{ inputs.token }}
