# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Filt < Formula
  desc "filt is a interactive/realtime stream filter."
  homepage "https://github.com/k1LoW/filt"
  version "0.8.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/k1LoW/filt/releases/download/v0.8.2/filt_v0.8.2_darwin_arm64.zip"
      sha256 "bf72725b231cc01a72b16c4ef4bada598189529f70ef4b7c0a5fbccf18c0489e"

      def install
        bin.install 'filt'
        output = Utils.safe_popen_read("#{bin}/filt", 'completion', 'bash')
        (bash_completion/'filt').write output
        output = Utils.safe_popen_read("#{bin}/filt", 'completion', 'zsh')
        (zsh_completion/'_filt').write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/filt/releases/download/v0.8.2/filt_v0.8.2_darwin_amd64.zip"
      sha256 "2579fcabf8ca89ed278500abe8489cf0d082b985a5b2e9065cfd45b3bd8ae324"

      def install
        bin.install 'filt'
        output = Utils.safe_popen_read("#{bin}/filt", 'completion', 'bash')
        (bash_completion/'filt').write output
        output = Utils.safe_popen_read("#{bin}/filt", 'completion', 'zsh')
        (zsh_completion/'_filt').write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/k1LoW/filt/releases/download/v0.8.2/filt_v0.8.2_linux_arm64.tar.gz"
      sha256 "f7e3e2951420f181a71e8d641087cd0eef8588eb9e017f4f4f8040067ed8624e"

      def install
        bin.install 'filt'
        output = Utils.safe_popen_read("#{bin}/filt", 'completion', 'bash')
        (bash_completion/'filt').write output
        output = Utils.safe_popen_read("#{bin}/filt", 'completion', 'zsh')
        (zsh_completion/'_filt').write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/k1LoW/filt/releases/download/v0.8.2/filt_v0.8.2_linux_amd64.tar.gz"
      sha256 "9c052ef5749960e5a848713fb143de75958fbbe95a277f778a741c3063e0d182"

      def install
        bin.install 'filt'
        output = Utils.safe_popen_read("#{bin}/filt", 'completion', 'bash')
        (bash_completion/'filt').write output
        output = Utils.safe_popen_read("#{bin}/filt", 'completion', 'zsh')
        (zsh_completion/'_filt').write output
      end
    end
  end
end
